language: elixir
elixir:
  - 1.8
  - 1.7
  - 1.6
  - 1.5
  - 1.4
  - 1.3
sudo: false
before_script:
  - mix deps.get --only test
env:
  - MIX_ENV=test
script:
  - mix coveralls.travis
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
